<?php // this is an autogenerated file - do not edit (created Tue, 12 Jul 2011 20:20:11 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'armbrustschütze' => '/units/player.php',
            'army' => '/army.php',
            'armyclivisitor' => '/army_visitor/cli.php',
            'armyfactory' => '/army_factory.php',
            'armyresult' => '/structs/army_result.php',
            'armyvisitor' => '/army_visitor.php',
            'beritteneamazone' => '/units/horsemen.php',
            'berittenerbogenschütze' => '/units/horsemen.php',
            'bogenschütze' => '/units/player.php',
            'brüllenderstier' => '/units/horsemen.php',
            'chuck' => '/units/barbarians.php',
            'clifightobserver' => '/fight_observer/cli.php',
            'desertiertemiliz' => '/units/traitors.php',
            'desertiertereiterei' => '/units/traitors.php',
            'desertierterlangbogenschütze' => '/units/traitors.php',
            'desertiertersoldat' => '/units/traitors.php',
            'dickebertha' => '/units/traitors.php',
            'diewildewaltraud' => '/units/barbarians.php',
            'einäugigerbert' => '/units/barbarians.php',
            'elitesoldat' => '/units/player.php',
            'fastunit' => '/fast_unit.php',
            'fight' => '/fighter.php',
            'fightobserver' => '/fight_observer.php',
            'fightoptimizer' => '/fighter/optimizer.php',
            'general' => '/units/player.php',
            'kanonier' => '/units/player.php',
            'kataphrakt' => '/units/horsemen.php',
            'kompositbogenschütze' => '/units/horsemen.php',
            'langbogenschütze' => '/units/player.php',
            'lanzenreiter' => '/units/horsemen.php',
            'metallgebiss' => '/units/barbarians.php',
            'miliz' => '/units/player.php',
            'multifight' => '/fighter/multi.php',
            'nomade' => '/units/horsemen.php',
            'observedfightoptimizer' => '/fighter/observed_optimizer.php',
            'optimizeresult' => '/structs/optimze_result.php',
            'plünderer' => '/units/barbarians.php',
            'raufbold' => '/units/barbarians.php',
            'reiterei' => '/units/player.php',
            'rekrut' => '/units/player.php',
            'result' => '/structs/result.php',
            'schläger' => '/units/barbarians.php',
            'sirrobin' => '/units/traitors.php',
            'soldat' => '/units/player.php',
            'steinwerfer' => '/units/barbarians.php',
            'stinktier' => '/units/barbarians.php',
            'unit' => '/unit.php',
            'unitresult' => '/structs/unit_result.php',
            'unitset' => '/unit_set.php',
            'wachhund' => '/units/barbarians.php',
            'waldläufer' => '/units/barbarians.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
