<?php // this is an autogenerated file - do not edit (created Sun, 20 Feb 2011 12:26:37 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'armbrustschütze' => '/units/player.php',
            'army' => '/army.php',
            'armyfactory' => '/army_factory.php',
            'armyprinter' => '/army_printer.php',
            'armyresult' => '/structs/army_result.php',
            'bogenschütze' => '/units/player.php',
            'chuck' => '/units/barbarians.php',
            'diewildewaltraud' => '/units/barbarians.php',
            'einäugigerbert' => '/units/barbarians.php',
            'elitesoldat' => '/units/player.php',
            'fastunit' => '/fast_unit.php',
            'fight' => '/fighter.php',
            'fightoptimizer' => '/fighter/optimizer.php',
            'general' => '/units/player.php',
            'kanonier' => '/units/player.php',
            'langbogenschütze' => '/units/player.php',
            'metallgebiss' => '/units/barbarians.php',
            'miliz' => '/units/player.php',
            'multifight' => '/fighter/multi.php',
            'optimizeresult' => '/structs/optimze_result.php',
            'plünderer' => '/units/barbarians.php',
            'raufbold' => '/units/barbarians.php',
            'reiterei' => '/units/player.php',
            'rekrut' => '/units/player.php',
            'result' => '/structs/result.php',
            'schläger' => '/units/barbarians.php',
            'soldat' => '/units/player.php',
            'steinwerfer' => '/units/barbarians.php',
            'stinktier' => '/units/barbarians.php',
            'unit' => '/unit.php',
            'unitresult' => '/structs/unit_result.php',
            'unitset' => '/unit_set.php',
            'wachhund' => '/units/barbarians.php',
            'waldläufer' => '/units/barbarians.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
