#!/usr/bin/env php
<?php

require __DIR__ . '/bootstrap.php';

if ( !isset( $argv[1] ) || !isset( $argv[2] ) )
{
    echo "You need to specify two army specification strings.", PHP_EOL;
    exit( 1 );
}

$attacker = ArmyFactory::factory( $argv[1] );
$defender = ArmyFactory::factory( $argv[2] );

$attacker->attack( $defender );

$printer = new ArmyPrinter();

$printer->visit( $attacker );
echo "\nversus:\n\n";
$printer->visit( $defender );

