#!/usr/bin/env php
<?php

require __DIR__ . '/bootstrap.php';

if ( !isset( $argv[1] ) || !isset( $argv[2] ) )
{
    echo "You need to specify two army specification strings.", PHP_EOL;
    exit( 1 );
}

$attacker = ArmyFactory::factory( $argv[1] );
$defender = ArmyFactory::factory( $argv[2] );

$optimzer = new ArmyOptimizer();
$results  = $optimzer->optimize( $attacker, $defender );

echo "Best results:\n\n";

$i = 0;
foreach ( $results['army'] as $nr => $army )
{
    echo $results['losses'][$nr], " losses:\n";
    $printer = new ArmyPrinter();
    $printer->visit( $army );
    echo "\n";

    if ( ++$i >= 10 ) return;
}

